### ISSUE TITLE
No errors but packages are not published?

### ISSUE THREAD

**Issue by LegendaryB** [rohith/publish-nuget#19]
Hey,

we are using your github action and everything seems fine. So build is running okay, packages are created but the update is not executed. Our NuGet secret has full permissions and is also found but no packages are published.

Do you know what the problem could be?
https://raw.githubusercontent.com/UltimateCodeMonkeys/CodeMonkeysMVVM/develop/.github/workflows/publish-nuget.yml

Kind Regards,
Daniel

**Comment by LegendaryB** [comment]
I will push it now manually but a response would be nice because we really want to use it in the future. Thanks for your time and keep up the good work!

**Comment by rohith** [comment]
Hey @LegendaryB I was away from GitHub (I guess I should turn on my email notifications)

I looked at the the workflow & it's repository, The action is unable to find the package as the project filenames are different from the nuget package names. You can be explicit about a package name with `PACKAGE_NAME` input. So your workflow should be updated to

```
- name: CodeMonkeys.Core
  uses: rohith/publish-nuget@dev
  with: 
    PROJECT_FILE_PATH: src/Core/Core.csproj
    TAG_COMMIT: false
    NUGET_KEY: ${{secrets.NUGET_API_KEY}}
    PACKAGE_NAME: CodeMonkeys.Core
```
