### ISSUE TITLE
Getting errors on publish task

### ISSUE THREAD

**Issue by johnazariah** [rohith/publish-nuget#20]
I'm sorry but I don't understand what I'm missing:

Here is my task:
```
name: Publish NuGet
      uses: rohith/publish-nuget@v2.2.0
      with:
        # Filepath of the project to be packaged, relative to root of repository
        PROJECT_FILE_PATH: universal-silo/universal-silo.fsproj
        # Filepath containing version info, relative to root of repository. Defaults to `PROJECT_FILE_PATH` if not specified
        VERSION_FILE_PATH: # optional
        # Regex (with version in a capturing group) to extract the version from `VERSION_FILE_PATH`
        VERSION_REGEX: # optional, default is <Version>(.*)<\/Version>
        # Bypasses version resolution; useful for external providers like Nerdbank.GitVersioning
        VERSION_STATIC: # optional
        # Whether to create a tag when there's a version change
        TAG_COMMIT: # optional, default is true
        # Format of the tag, `*` is the placeholder for actual version
        TAG_FORMAT: # optional, default is v*
        # API key for the NuGet feed
        NUGET_KEY: # optional
        # NuGet package name, required when it's different from the project name
        PACKAGE_NAME: Orleans.Contrib.UniversalSilo
```

I've set the nuget key as a secret named NUGET_API_KEY in the project settings.

When the action is run, I get the result:

```
Run rohith/publish-nuget@v2.2.0
  with:
    PROJECT_FILE_PATH: universal-silo/universal-silo.fsproj
    PACKAGE_NAME: Orleans.Contrib.UniversalSilo
  env:
    DOTNET_ROOT: /opt/hostedtoolcache/dncs/3.1.101/x64
undefined:1
undefined
^

SyntaxError: Unexpected token u in JSON at position 0
    at JSON.parse (<anonymous>)
    at new Action (/home/runner/work/_actions/rohith/publish-nuget/v2.2.0/index.js:12:32)
    at Object.<anonymous> (/home/runner/work/_actions/rohith/publish-nuget/v2.2.0/index.js:130:1)
    at Module._compile (internal/modules/cjs/loader.js:959:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Function.Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1047:10)
    at internal/main/run_main_module.js:17:11
```
