### ISSUE TITLE
Publish multiple projects

### ISSUE THREAD

**Issue by drjaydenm** [rohith/publish-nuget#9]
At the moment, I can only see a way to support a single project being published per repo (unless I was to change the version format for every package to avoid collisions).

Would it be possible to allow multiple project/package support? Or maybe just a way to disable the git tagging step for every project after the first one?

**Comment by rohith** [comment]
I see the problem, supporting multiple projects/packages shouldn't be hard, I'll see what can be done

To disable git tagging after main project the action needs to know which is the main project. This info can be provided via the `yaml` config. Does it sound good or do you prefer some other way to do it?

**Comment by drjaydenm** [comment]
Yeah that sounds like it should work, maybe as simple as a boolean flag to toggle the git tagging check/step. At the moment, my config looks like this
```yaml
- name: Publish Project.Core
  uses: rohith/publish-nuget@v1
  with:
    project_dir: Project.Core
    nuget_key: ...
- name: Publish Project.Extension
  uses: rohith/publish-nuget@v1
  with:
    project_dir: Project.Extension
    nuget_key: ...
```
In the second project pack/push it blows up due to the tag existing from the previous step
